name: TWRP Builder for Raphael

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # --- DÜZELTİLEN KISIM (Disk Temizleme) ---
    - name: Disk Alanını Temizle (Clean Up)
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
    # ------------------------------------------

    - name: Derleme Ortamını Hazırla
      run: |
        sudo apt update
        sudo apt -y install git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

    - name: Repo Aracını Kur
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Git Konfigürasyonu
      run: |
        git config --global user.name "CI Builder"
        git config --global user.email "ci@example.com"

    - name: Kaynak Kodlarını İndir (Sync)
      run: |
        mkdir work
        cd work
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 --depth=1
        repo sync -j$(nproc --all) --force-sync

    # --- DÜZELTİLEN KISIM (Klasör Oluşturma) ---
    - name: Cihaz Ağacını Klonla
      run: |
        cd work
        # Hata almamak için önce klasörü oluşturuyoruz
        mkdir -p device/xiaomi
        git clone https://github.com/HeliumStudio-Dev/twrp_device_xiaomi_raphael device/xiaomi/raphael
    # -------------------------------------------

    - name: Derlemeyi Başlat
      run: |
        cd work
        export ALLOW_MISSING_DEPENDENCIES=true
        . build/envsetup.sh
        lunch twrp_raphael-eng
        mka recoveryimage

    - name: Dosyayı Yükle (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Raphael-Build
        path: work/out/target/product/raphael/*.img
